### ISSUE TITLE
java.lang.IllegalStateException: attempt to use Deflater after calling end

### ISSUE THREAD

**Issue by rotman** [andrewhayden/archive-patcher#11]
When I try the generate a Patch with the Generating a Patch sample code,
The app crash with the the following exception:
`FATAL EXCEPTION: main
                                                                                       Process: com.rotem.deltaupdatepoc2, PID: 6614
                                                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rotem.deltaupdatepoc2/com.rotem.deltaupdatepoc2.MainActivity}: java.lang.IllegalStateException: attempt to use Deflater after calling end
                                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                           at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                        Caused by: java.lang.IllegalStateException: attempt to use Deflater after calling end
                                                                                           at java.util.zip.Deflater.checkOpen(Deflater.java:476)
                                                                                           at java.util.zip.Deflater.reset(Deflater.java:355)
                                                                                           at com.google.archivepatcher.generator.DefaultDeflateCompressionDiviner.divineDeflateParameters(DefaultDeflateCompressionDiviner.java:183)
                                                                                           at com.google.archivepatcher.generator.DefaultDeflateCompressionDiviner.divineDeflateParameters(DefaultDeflateCompressionDiviner.java:104)
                                                                                           at com.google.archivepatcher.generator.PreDiffExecutor.generatePreDiffPlan(PreDiffExecutor.java:216)
                                                                                           at com.google.archivepatcher.generator.PreDiffExecutor.prepareForDiffing(PreDiffExecutor.java:157)
                                                                                           at com.google.archivepatcher.generator.FileByFileV1DeltaGenerator.generateDelta(FileByFileV1DeltaGenerator.java:81)
                                                                                           at com.rotem.deltaupdatepoc2.SamplePatchGenerator.generatePatch(SamplePatchGenerator.java:39)
                                                                                           at com.rotem.deltaupdatepoc2.MainActivity.cheackForPermissions(MainActivity.java:48)
                                                                                           at com.rotem.deltaupdatepoc2.MainActivity.onCreate(MainActivity.java:20)
                                                                                           at android.app.Activity.performCreate(Activity.java:6237)
                                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                           at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                           at android.os.Looper.loop(Looper.java:148) 
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) `

Can anyone help please?

**Comment by andrewhayden** [comment]
@rotman, can you attach the files to reproduce this?

**Comment by rotman** [comment]
`public class SamplePatchGenerator {

	private String mPatchFilePath;

	public SamplePatchGenerator(Context context) {
		if (!new DefaultDeflateCompatibilityWindow().isCompatible()) {
			Log.e(MainActivity.TAG, "zlib not compatible on this system");
		}
		else {
			mPatchFilePath = context.getFilesDir() + "/patch";
		}
	}

	public void generatePatch(String oldFilePath, String newFilePath) {
		File oldFile = new File(oldFilePath);
		File newFile = new File(newFilePath);
		Deflater compressor = new Deflater(9, true); // to compress the patch
		try {
			try (FileOutputStream patchOut = new FileOutputStream(mPatchFilePath) ;
			     DeflaterOutputStream compressedPatchOut = new DeflaterOutputStream(patchOut, compressor, 32768)) {
				new FileByFileV1DeltaGenerator().generateDelta(oldFile, newFile, compressedPatchOut);
				compressedPatchOut.finish();
				compressedPatchOut.flush();
			} finally {
				compressor.end();
			}
		} catch (IOException e) {
			Log.e(MainActivity.TAG, e.getMessage());
		} catch (InterruptedException e) {
			Log.e(MainActivity.TAG, e.getMessage());
		}
	}
}`

`SamplePatchGenerator samplePatchGenerator = new SamplePatchGenerator(this);
samplePatchGenerator.generatePatch("/sdcard/release_V2.9.1.apk", "/sdcard/release_V2.11.apk");`

**Comment by rotman** [comment]
Hi @andrewhayden 
Any update?

**Comment by andrewhayden** [comment]
Hi @rotman, sorry, to be clear, I was hoping to get the inputs (e.g., release_V2.9.1.apk and release_V2.11.apk) you are using that are generating this error. Is that possible?

**Comment by andrewhayden** [comment]
Also, note that the patch _generator_ was not originally intended to run on Android. The expectation is that patch _generation_ is done off-device. It should be possible to run it on an Android device, but there may be subtle differences in the implementation of java.util.zip that are at play here.

**Comment by andrewhayden** [comment]
@canamaria can provide more context on this. I believe this has a fix internally that would be a candidate for upstreaming.

**Comment by canamaria** [comment]
Hi everyone!

I have just upstreamed a bug fix which should resolve the issue. The Deflater within DefaultDeflateCompressionDiviner was not explicitly terminated by calling end() meaning we were relying on the GC to free memory, which was causing problems. 

See [this](https://bugs.openjdk.java.net/browse/JDK-8074108) for more details.

Thanks,
Ana
